version: "3.8"

services:
  db:
    image: postgres:16
    container_name: acmevita-db
    environment:
      POSTGRES_DB: acmevita
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: acmevita-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/acmevita

volumes:
  postgres_data:
